name: stack_trace_parser
description: A library to parse stack traces in various formats
version: 0.0.1
homepage: https://github.com/ueman/stack_trace_parser
issue_tracker: https://github.com/ueman/stack_trace_parser/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
